# Generated by Django 5.2.12 on 2026-03-19 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_product_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='total_quantity',
        ),
    ]
